spring.application.name=stin-currency-project

server.port=8198
app.storage.path=.

spring.security.user.name=uzivatel
spring.security.user.password=uzivatelskeHeslo135

exchange.api.base-url=https://api.exchangerate.host
exchange.api.key=${EXCHANGE_API_KEY}